version: '3.9'
services:
  web:
    build: .
    image: recipes-app/web
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - DB_HOST=db
      - DB_NAME=recipes
      - DB_USER=postgres
      - DB_PASSWORD=s3cret
    depends_on:
      - db
  db:
    image: postgres:9.6.24-alpine
    environment:
      - POSTGRES_DB=recipes
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=s3cret
    